name: dbmigrate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  db-migrate:
    runs-on: ubuntu-latest
    name: db migrate
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Installing dependencies
        run: npm install
        
      - name: installing sequelize cli
        run: npm install --save sequelize-cli 
        
      - name: "Migrating db"
        run: npx sequelize-cli db:migrate
